### ISSUE TITLE
login -u flag

### ISSUE THREAD

**Issue by johnfonner** [jturcino/vdj-cli#1]
The username in the cache file seems to override a username given by the -u flag.  Ideally, the behavior should be that specifying a username at the command line would override what is in the cache, and if the -s flag is present, it should end up overwriting the cache file.

**Comment by jturcino** [comment]
Rewrote args to resolve issue. Fixed with commit [a1ca8437047fef088cfede161c4940e18f10033f](https://github.com/jturcino/vdj-cli/commit/a1ca8437047fef088cfede161c4940e18f10033f).
